service: IFTTT

provider:
  name: dronedeploy

custom:
  appId: # APP ID goes here

plugins:
  - "serverless-dronedeploy"

package:
  individually: true
  exclude:
    - node_modules/**

functions:
  webhook:
    name: "ifttt-webhook"
    handlerPath: functions/webhook
    handler: webhook
    app: # APP ID goes here
    memory: 128
    resources:
      tables:
        webhook-table:
          description: "stores endpoint for IFTTT webhook"
          columns:
            - name: endpoint
              type: Text
              encrypted: false
              length: 255
              description: "webhook endpoint for IFTTT"

