service: IFTT

provider:
  name: dronedeploy

app: chhxvitfdztlooxgisee

plugins:
  - "@dronedeploy/dronedeploy-cli"

functions:
  cartogram-webhook:
    handlerPath: functions/webhook
    handler: dronedeploy
    memory: 128
    events:
      - trigger:
          object-type: Export
          type: complete
    resources:
      tables:
        webhook-table:
          description: "stores endpoint for storing cartogram"
          columns:
            - name: endpoint
              type: Text
              encrypted: false
              length: 255
              description: "storage endpoint for cartogram"
