service: IFTTT

provider:
  name: dronedeploy

custom:
  appId: abodazipgumvteodzohl

plugins:
  - "serverless-dronedeploy"

functions:
  webhook:
    name: "ifttt-webhook"
    handler: webhook
    memory: 128
    app: abodazipgumvteodzohl
    package:
      individually: true
      exclude:
        - node_modules/**
      include:
        - serverless.yml
    resources:
      tables:
        webhook-table:
          description: "stores endpoint for IFTTT webhook"
          columns:
            - name: endpoint
              type: Text
              encrypted: false
              length: 255
              description: "webhook endpoint for IFTTT"